# Generated by Django 4.2.3 on 2023-08-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 50 characters', 'null': 'This field must not be empty'}, max_length=50)),
                ('starting_price', models.FloatField(error_messages={'blank': 'This field must not be empty', 'null': 'This field must not be empty'})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_which_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_which_belongs', to='restaurant_control.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Food Category',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 50 characters', 'null': 'This field must not be empty'}, max_length=50)),
                ('price', models.FloatField(error_messages={'blank': 'This field must not be empty', 'null': 'This field must not be empty'})),
                ('time_to_make', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category_belongs', to='food_control.foodcategory')),
                ('restaurant_belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_belongs_to', to='restaurant_control.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Food',
                'ordering': ('-created_at',),
            },
        ),
    ]
