# Generated by Django 4.2.3 on 2023-08-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(error_messages={'blank': 'This field must not be empty', 'max_length': 'This field must not be more than 50 characters', 'null': 'This field must not be empty', 'unique': 'This restaurant name has already been registered'}, max_length=50, unique=True),
        ),
    ]
