# Generated by Django 4.2.3 on 2023-08-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_control', '0002_alter_restaurant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
    ]
