# Generated by Django 4.2.3 on 2023-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_control', '0003_rename_location_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='we are the best at what we do', error_messages={'blank': 'This field must not be empty', 'null': 'This field must not be empty'}),
        ),
    ]
