version: '3'

services:
  food_app:
    container_name: food_app
    image: postgres
    environment:
      POSTGRES_USER: "food_user"
      POSTGRES_PASSWORD: "food_user123"
      PGDATA: /data/food_app
    volumes:
      - food_app:/data/food_app
    ports:
      - "5434:5432"
    networks:
      - food_app_net
    restart: unless-stopped

networks:
  food_app_net:
    driver: bridge

volumes:
  food_app: